### ISSUE TITLE
How to get Readingtime to work with Action Text?

### ISSUE THREAD

**Issue by marekdlugos** [garethrees/readingtime#12]
_Disclaimer_: I am a newbie to Rails.

I am wondering how to get readingtime to work with Action Text. I have had readingtime set up and running but once I have implemented the Action Text I am getting the following error:

```
NoMethodError at /articles/how-are-things
undefined method `reading_time' for #<ActionText::RichText:0x00007fb5a7be63b0>
```

**Comment by garethrees** [comment]
Looks like you'll need to call [`#to_plain_text`](https://edgeapi.rubyonrails.org/classes/ActionText/RichText.html#method-i-to_plain_text) first – I guess something like:

```erb
<%= @article.content.to_plain_text.reading_time %>
```

I haven't used ActionText at all, so let me know if that works or not 👍.

**Comment by marekdlugos** [comment]
Yay! It worked, thank a lot! You may close this now.
