### ISSUE TITLE
Different words per minute for faster/slower readers

### ISSUE THREAD

**Issue by owainlewis** [garethrees/readingtime#4]
Random idea. Might be nice to pass in the 200 average words per minute as an option?

Average readers

```ruby
@article.body.reading_time :format => :basic, :wpm 200
```
For fast readers

```ruby
@article.body.reading_time :format => :basic, :wpm 300
```

**Comment by wkoffel** [comment]
Not just for various readers, but also for cases where you know the content is more dense, with lots of diagrams that take time to digest, etc. (slower) or easy to skim, lots of repeated text, etc. (faster)

**Comment by garethrees** [comment]
#7 goes some way to address this – I'll try to add it as an option arg if I get time
